server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my_db
    username: root
    password: wxl3322335
    type: com.alibaba.druid.pool.DruidDataSource



mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: com.test.tableau.Mapper